// autoconf.h generated from config-alnwlsn-custom at Thu Apr 21 00:41:18 2022

#ifndef AUTOCONF_H
#define AUTOCONF_H

#define CONFFILES configs/config-alnwlsn-custom
#define CONFIG_ARCH avr
#define CONFIG_BOOT_DEVID 0x49454321
#define CONFIG_BUFFER_COUNT 6
#define CONFIG_COMMAND_BUFFER_SIZE 120
#define CONFIG_COMMAND_CHANNEL_DUMP
#define CONFIG_DISPLAY_BUFFER_SIZE 40
#define CONFIG_ERROR_BUFFER_SIZE 100
#define CONFIG_HARDWARE_NAME sd2iec-alnwlsn
#define CONFIG_HARDWARE_VARIANT 9
#define CONFIG_HAVE_IEC
#define CONFIG_LOADER_AR6
#define CONFIG_LOADER_DREAMLOAD
#define CONFIG_LOADER_ELOAD1
#define CONFIG_LOADER_EPYXCART
#define CONFIG_LOADER_FC3
#define CONFIG_LOADER_GEOS
#define CONFIG_LOADER_GIJOE
#define CONFIG_LOADER_MMZAK
#define CONFIG_LOADER_N0SDOS
#define CONFIG_LOADER_NIPPON
#define CONFIG_LOADER_SAMSJOURNEY
#define CONFIG_LOADER_TURBODISK
#define CONFIG_LOADER_ULOAD3
#define CONFIG_LOADER_WHEELS
#define CONFIG_MAX_PARTITIONS 4
#define CONFIG_MCU atmega644
#define CONFIG_MCU_FREQ 8000000
#define CONFIG_SD_AUTO_RETRIES 10
#define CONFIG_SD_DATACRC
#define CONFIG_UART_BAUDRATE 19200
#define CONFIG_UART_BUF_SHIFT 6

#endif
