#define INT0 0
#define INT1 1
#define INT2 2
#define IEC_PCMSK PCMSK0
#define PRADC 0
#define ARCH_CONFIG_H 
#define OCF0B 2
#define IEC_BIT_CLOCK _BV(IEC_PIN_CLOCK)
#define OCF1A 1
#define OCF1B 2
#define CONFIG_MCU_FREQ 8000000
#define OCF2B 2
#define FUSE_BOOTRST (unsigned char)~_BV(0)
#define HAVE_CLOCK_IRQ 
#define IEC_OBIT_ATN _BV(IEC_OPIN_ATN)
#define EEAR _SFR_IO16(0x21)
#define FE0 4
#define FE1 4
#define ACI 4
#define EECR _SFR_IO8(0x1F)
#define EEDR _SFR_IO8(0X20)
#define IEC_OBIT_CLOCK _BV(IEC_OPIN_CLOCK)
#define ANALOG_COMP_vect _VECTOR(23)
#define IEC_PIN_SRQ PA3
#define TIMER0_OVF_vect _VECTOR(18)
#define AVR_STACK_POINTER_HI_ADDR _SFR_IO_ADDR(SPH)
#define SPCR _SFR_IO8(0x2C)
#define FUSE_WDTON (unsigned char)~_BV(4)
#define USART1_UDRE_vect_num 29
#define P00CACHE_ATTRIB 
#define SPDR _SFR_IO8(0x2E)
#define ACBG 6
#define SD2_CHANGE_HANDLER ISR(INT2_vect)
#define SLEEP_MODE_STANDBY (0x06<<1)
#define TIMER1_CAPT_vect _VECTOR(12)
#define CONFIG_SD_AUTO_RETRIES 10
#define SREG_C (0)
#define SREG_H (5)
#define SREG_I (7)
#define SREG_N (2)
#define SREG_S (4)
#define SREG_T (6)
#define SREG_V (3)
#define SREG_Z (1)
#define OCDR _SFR_IO8(0x31)
#define USART1_UDRE_vect _VECTOR(29)
#define PORTA0 PA0
#define PORTA1 PA1
#define PORTA2 PA2
#define PORTA3 PA3
#define PORTA4 PA4
#define PORTA5 PA5
#define PORTA6 PA6
#define CONFIG_LOADER_GEOS 
#define HWI2C_SCL _BV(PC0)
#define SPIE 7
#define SPIF 7
#define FUSE_BOOTSZ0 (unsigned char)~_BV(1)
#define FUSE_BOOTSZ1 (unsigned char)~_BV(2)
#define PORTB2 PB2
#define PORTB3 PB3
#define PORTB4 PB4
#define PORTB5 PB5
#define PORTB6 PB6
#define PORTB7 PB7
#define TXB80 0
#define TXB81 0
#define reti() __asm__ __volatile__ ("reti" ::)
#define BORF 2
#define CS00 0
#define CS01 1
#define PORTC0 PC0
#define PORTC1 PC1
#define PORTC2 PC2
#define PORTC3 PC3
#define PORTC4 PC4
#define PORTC5 PC5
#define PORTC6 PC6
#define PORTC7 PC7
#define INT2_vect _VECTOR(3)
#define CS10 0
#define CS11 1
#define CS12 2
#define PORTD0 PD0
#define PORTD1 PD1
#define PORTD2 PD2
#define PORTD4 PD4
#define PORTD5 PD5
#define PORTD6 PD6
#define ACIC 2
#define ACIE 3
#define CS20 0
#define CS21 1
#define CS22 2
#define SPI_DDR DDRB
#define EEPE 1
#define HAVE_HOTPLUG 
#define MPCM0 0
#define MPCM1 0
#define TIMER1_CAPT_vect_num 12
#define EERE 0
#define SOFTI2C_DDR DDRC
#define ACME 6
#define CONFIG_LOADER_FC3 
#define SPI_DIVISOR_SLOW 32
#define PIN0 0
#define PIN1 1
#define PIN2 2
#define PIN3 3
#define PIN4 4
#define PIN5 5
#define PIN6 6
#define PIN7 7
#define PINA _SFR_IO8(0X00)
#define PINB _SFR_IO8(0X03)
#define PINC _SFR_IO8(0x06)
#define PIND _SFR_IO8(0x09)
#define PCINT1_vect_num 5
#define SPR0 0
#define SPR1 1
#define TCR2BUB 0
#define E2PAGESIZE 8
#define _AVR_FUSE_H_ 1
#define SPSR _SFR_IO8(0x2D)
#define IEC_PIN_ATN PA0
#define CONFIG_MCU atmega644p
#define IVCE 0
#define PCINT6 6
#define ACSR _SFR_IO8(0x30)
#define UPM00 4
#define UPM01 5
#define CONFIG_LOADER_GIJOE 
#define FOC0A 7
#define FOC0B 6
#define UPM10 4
#define UPM11 5
#define FOC1A 7
#define FOC1B 6
#define AUTOCONF_H 
#define RXEN0 4
#define RXEN1 4
#define TWGCE 0
#define CONFIG_ERROR_BUFFER_SIZE 100
#define FOC2A 7
#define FOC2B 6
#define WDT_vect_num 8
#define USART1_RX_vect_num 28
#define cli() __asm__ __volatile__ ("cli" ::: "memory")
#define SPI_STC_vect_num 19
#define EIFR _SFR_IO8(0x1C)
#define TCR2AUB 1
#define EE_READY_vect_num 25
#define CONFIG_DISPLAY_BUFFER_SIZE 40
#define _AVR_SFR_DEFS_H_ 1
#define USART_RX_vect USART0_RX_vect
#define set_clock_irq(x) if (x) { IEC_PCMSK |= _BV(IEC_PIN_CLOCK); } else { IEC_PCMSK &= (uint8_t)~_BV(IEC_PIN_CLOCK); }
#define _AVR_IOMXX4_H_ 1
#define PGWRT 2
#define COM0A0 6
#define COM0A1 7
#define SPI_SS _BV(PB4)
#define ADATE 5
#define COM0B0 4
#define COM0B1 5
#define FUSE_CKSEL0 (unsigned char)~_BV(0)
#define FUSE_CKSEL1 (unsigned char)~_BV(1)
#define FUSE_CKSEL2 (unsigned char)~_BV(2)
#define FUSE_CKSEL3 (unsigned char)~_BV(3)
#define _SFR_IO8(io_addr) ((io_addr) + __SFR_OFFSET)
#define TIMER0_COMPB_vect_num 17
#define PCINT0 0
#define PCINT1 1
#define PCINT2 2
#define PCINT3 3
#define PCINT4 4
#define PCINT5 5
#define PCINT7 7
#define PCINT8 0
#define PCINT9 1
#define UCSR0A _SFR_MEM8(0xC0)
#define UCSR0B _SFR_MEM8(0XC1)
#define UCSR0C _SFR_MEM8(0xC2)
#define _AVR_PORTPINS_H_ 1
#define CONFIG_ARCH avr
#define SLEEP_MODE_PWR_DOWN (0x02<<1)
#define UCSR1A _SFR_MEM8(0xC8)
#define UCSR1B _SFR_MEM8(0XC9)
#define UCSR1C _SFR_MEM8(0xCA)
#define SPI2X 0
#define JTD 7
#define SYSTEM_TICK_HANDLER ISR(TIMER1_COMPA_vect)
#define WDCE 4
#define NDEBUG 
#define OCF0A 1
#define SPI_SCK _BV(PB7)
#define MAX_DRIVES 8
#define EICRA _SFR_MEM8(0x69)
#define EEPROMFS_SIZE 3584
#define XRAMEND RAMEND
#define ISC10 2
#define ISC11 3
#define SPI_STC_vect _VECTOR(19)
#define TOV0 0
#define TOV1 0
#define TOV2 0
#define IEC_OUTPUT IEC_PORT
#define PINB6 6
#define ISC20 4
#define EXTRF 1
#define WDIE 6
#define WDIF 7
#define CONFFILES configs/config-alnwlsn-custom
#define IEC_ATN_INT_VECT PCINT0_vect
#define SOFTI2C_PORT PORTC
#define EEARH _SFR_IO8(0X22)
#define RXB80 1
#define RXB81 1
#define EEARL _SFR_IO8(0x21)
#define PGERS 1
#define RAMSTART (0x100)
#define SMCR _SFR_IO8(0x33)
#define SIGNAL(vector) void vector (void) __attribute__ ((signal, __INTR_ATTRS)); void vector (void)
#define AVR_STATUS_REG SREG
#define TIMER0_COMPA_vect _VECTOR(16)
#define WDP0 0
#define WDP1 1
#define WDP2 2
#define WDP3 5
#define CLKPS0 0
#define PCINT0_vect_num 4
#define CONFIG_LOADER_DREAMLOAD 
#define IEC_OPIN_SRQ PA7
#define CONFIG_UART_BUF_SHIFT 6
#define SLEEP_MODE_ADC (0x01<<1)
#define WDRF 3
#define RXCIE1 7
#define IDRD 7
#define ZH r31
#define RWWSRE 4
#define OCR1AH _SFR_MEM8(0x89)
#define OCR1AL _SFR_MEM8(0x88)
#define UCSRA UCSR0A
#define UCSRC UCSR0C
#define OCR1BH _SFR_MEM8(0x8B)
#define OCR1BL _SFR_MEM8(0x8A)
#define SIGRD 5
#define ADPS0 0
#define ADPS1 1
#define _VECTOR(N) __vector_ ## N
#define IEC_INPUT PINA
#define TCNT1H _SFR_MEM8(0x85)
#define _AVR_IOXXX_H_ "iom164.h"
#define _SFR_MEM8(mem_addr) (mem_addr)
#define FUSE_JTAGEN (unsigned char)~_BV(6)
#define ISC21 5
#define CONFIG_LOADER_ELOAD1 
#define PRTWI 7
#define FUSE_BODLEVEL0 (unsigned char)~_BV(0)
#define FUSE_BODLEVEL1 (unsigned char)~_BV(1)
#define FUSE_BODLEVEL2 (unsigned char)~_BV(2)
#define OCR0A _SFR_IO8(0X27)
#define OCR0B _SFR_IO8(0X28)
#define UDRE0 5
#define UDRE1 5
#define OCR1A _SFR_MEM16(0x88)
#define OCR1B _SFR_MEM16(0x8A)
#define INTF0 0
#define INTF1 1
#define INTF2 2
#define UCSZ0 UCSZ00
#define UCSZ1 UCSZ01
#define OCR2A _SFR_MEM8(0xB3)
#define OCR2B _SFR_MEM8(0xB4)
#define TIMER0_COMPA_vect_num 16
#define IEC_PIN_DATA PA1
#define CONFIG_MAX_PARTITIONS 4
#define EEPM0 4
#define EEPM1 5
#define _AVR_INTERRUPT_H_ 
#define BUTTON_NEXT _BV(PC3)
#define ICES1 6
#define UDRIE UDRIE0
#define TWA0 1
#define TWA1 2
#define TWA2 3
#define TWA3 4
#define TWA4 5
#define TWA5 6
#define TWA6 7
#define TWAR _SFR_MEM8(0xBA)
#define TWBR _SFR_MEM8(0xB8)
#define IEC_OPIN_ATN PA4
#define FUSE_MEMORY_SIZE 3
#define TWCR _SFR_MEM8(0xBC)
#define USBS0 3
#define USBS1 3
#define TWDR _SFR_MEM8(0xBB)
#define TWEA 6
#define TIMER0_COMPB_vect _VECTOR(17)
#define _AVR_COMMON_H 
#define TWEN 2
#define EEPROMFS_OFFSET 512
#define ADCH _SFR_MEM8(0x79)
#define ADCL _SFR_MEM8(0x78)
#define ADCW _SFR_MEM16(0x78)
#define PINA0 0
#define PINA1 1
#define PINA2 2
#define PINA3 3
#define PINA4 4
#define PINA5 5
#define PINA6 6
#define PINA7 7
#define CONFIG_HARDWARE_VARIANT 5
#define OCF2A 1
#define PINB0 0
#define PINB1 1
#define PINB2 2
#define PINB3 3
#define PINB4 4
#define PINB5 5
#define PINB7 7
#define MCUCR _SFR_IO8(0X35)
#define _VECTORS_SIZE 124
#define ADEN 7
#define PINC0 0
#define PINC1 1
#define PINC2 2
#define PINC3 3
#define PINC4 4
#define PINC5 5
#define PINC6 6
#define PINC7 7
#define AVR_STACK_POINTER_HI_REG SPH
#define PIND0 0
#define PIND1 1
#define PIND2 2
#define PIND3 3
#define PIND4 4
#define PIND5 5
#define PIND6 6
#define PIND7 7
#define TWIE 0
#define DDC2 2
#define ICIE1 5
#define CPHA 2
#define ADIE 3
#define ADIF 4
#define AVR_STACK_POINTER_ADDR _SFR_IO_ADDR(SP)
#define SPMEN 0
#define MUX0 0
#define MUX1 1
#define MUX2 2
#define MUX3 3
#define ICR1L _SFR_MEM8(0x86)
#define UDRIE0 5
#define UDRIE1 5
#define PORTA7 PA7
#define TCCR0A _SFR_IO8(0x24)
#define TCCR0B _SFR_IO8(0x25)
#define ADC_vect_num 24
#define UCSZ00 1
#define UCSZ01 2
#define UCSZ02 2
#define AIN0D 0
#define ADTS0 0
#define ADTS2 2
#define TCCR1A _SFR_MEM8(0x80)
#define TCCR1B _SFR_MEM8(0x81)
#define TCCR1C _SFR_MEM8(0x82)
#define UCSZ10 1
#define UCSZ11 2
#define UCSZ12 2
#define AIN1D 1
#define _AVR_IOM644P_H_ 1
#define TCCR2A _SFR_MEM8(0xB0)
#define TCCR2B _SFR_MEM8(0xB1)
#define SPMIE 7
#define INT2_vect_num 3
#define AVR_STACK_POINTER_LO_REG SPL
#define CPOL 3
#define OCR2AUB 3
#define TWS3 3
#define TWS4 4
#define TWS5 5
#define TWS6 6
#define TWS7 7
#define TWSR _SFR_MEM8(0xB9)
#define TWI_vect_num 26
#define IEC_PORT PORTA
#define UCPOL0 0
#define UCPOL1 0
#define DDA0 0
#define DDA1 1
#define DDA2 2
#define DDA3 3
#define DDA4 4
#define DDA5 5
#define DDA6 6
#define DDA7 7
#define RXC RXC0
#define MCUSR _SFR_IO8(0x34)
#define ADSC 6
#define DDB0 0
#define DDB1 1
#define DDB2 2
#define DDB3 3
#define DDB4 4
#define DDB5 5
#define DDB6 6
#define DDB7 7
#define DDC0 0
#define DDC1 1
#define DDC3 3
#define DDC4 4
#define DDC5 5
#define DDC6 6
#define DDC7 7
#define TWWC 3
#define SOFTI2C_PIN PINC
#define DDD0 0
#define DDD1 1
#define DDD2 2
#define DDD3 3
#define DDD4 4
#define DDD5 5
#define DDD6 6
#define DDD7 7
#define CONFIG_HAVE_IEC 
#define WDE 3
#define _SFR_IO_REG_P(sfr) ((sfr) < 0x40 + __SFR_OFFSET)
#define HWI2C_PORT PORTC
#define TIMER2_COMPB_vect_num 10
#define CONFIG_BOOT_DEVID 0x49454321
#define PORTB1 PB1
#define UCPHA1 1
#define _SFR_ASM_COMPAT 1
#define USART0_RX_vect_num 20
#define COM1A0 6
#define COM1A1 7
#define COM1B0 4
#define COM1B1 5
#define FLASHEND 0xFFFF
#define CONFIG_LOADER_MMZAK 
#define CLKPCE 7
#define TXCIE0 6
#define TXCIE1 6
#define RAMEND 0x10FF
#define TWI_vect _VECTOR(26)
#define IEC_BIT_DATA _BV(IEC_PIN_DATA)
#define CONFIG_SD_DATACRC 
#define IEC_CLOCK_HANDLER ISR(IEC_CLK_INT_VECT)
#define PCINT0_vect _VECTOR(4)
#define CONFIG_BUFFER_COUNT 6
#define ADMUX _SFR_MEM8(0x7C)
#define HWI2C_SDA _BV(PC1)
#define SPM_READY_vect _VECTOR(27)
#define OCIE0A 1
#define OCIE0B 2
#define _AVR_IO_H_ 
#define SPI_DIVISOR_FAST 4
#define OCIE1A 1
#define OCIE1B 2
#define SPI_MOSI _BV(PB5)
#define DDRA _SFR_IO8(0X01)
#define DDRB _SFR_IO8(0x04)
#define DDRC _SFR_IO8(0x07)
#define DDRD _SFR_IO8(0x0A)
#define OCIE2B 2
#define HAVE_SD 
#define LFUSE_DEFAULT (FUSE_CKSEL0 & FUSE_CKSEL2 & FUSE_CKSEL3 & FUSE_SUT0 & FUSE_SUT1 & FUSE_CKDIV8)
#define _HAVE_AVR_STACK_POINTER_HI 1
#define _SFR_IO16(io_addr) ((io_addr) + __SFR_OFFSET)
#define DD0 0
#define DD1 1
#define DD2 2
#define DD3 3
#define DD4 4
#define DD5 5
#define DD6 6
#define DD7 7
#define DOR0 3
#define DOR1 3
#define _SFR_IO_ADDR(sfr) ((sfr) - __SFR_OFFSET)
#define DORD 5
#define ANALOG_COMP_vect_num 23
#define IEC_PIN_CLOCK PA2
#define USART1_TX_vect _VECTOR(30)
#define TWSTA 5
#define TWSTO 4
#define sei() __asm__ __volatile__ ("sei" ::: "memory")
#define CONFIG_LOADER_TURBODISK 
#define IEC_PORTIN IEC_PORT
#define CS02 2
#define EEMPE 2
#define CONFIG_LOADER_N0SDOS 
#define OCIE2A 1
#define FUSE_EESAVE (unsigned char)~_BV(3)
#define ISR_BLOCK 
#define CLKPS1 1
#define CLKPS2 2
#define CLKPS3 3
#define ASSR _SFR_MEM8(0xB6)
#define USART1_RX_vect _VECTOR(28)
#define BUTTON_PREV _BV(PC2)
#define E2END 0x7FF
#define INT1_vect_num 2
#define IEC_OPIN_CLOCK PA6
#define IEEE_ATN_HANDLER ISR(IEEE_ATN_INT_VECT)
#define TWAM0 1
#define TWAM1 2
#define TWAM2 3
#define TWAM3 4
#define TWAM4 5
#define TWAM5 6
#define EXCLK 6
#define TWAMR _SFR_MEM8(0xBD)
#define SPI_PORT PORTB
#define TIMER0_OVF_vect_num 18
#define CONFIG_LOADER_EPYXCART 
#define UDR0 _SFR_MEM8(0XC6)
#define UDR1 _SFR_MEM8(0XCE)
#define SPM_READY_vect_num 27
#define toggle_srq() IEC_INPUT |= IEC_OBIT_SRQ
#define IEC_SEPARATE_OUT 
#define DIDR0 _SFR_MEM8(0x7E)
#define DIDR1 _SFR_MEM8(0x7F)
#define SOFTI2C_BIT_SCL PC4
#define SOFTI2C_BIT_SDA PC5
#define PCINT1_vect _VECTOR(5)
#define EFUSE_DEFAULT (0xFF)
#define TIMER1_COMPA_vect _VECTOR(13)
#define TIMER2_COMPA_vect_num 9
#define UDR UDR0
#define TIMER1_OVF_vect_num 15
#define IEC_DDR DDRA
#define IEC_DDRIN IEC_DDR
#define ADC0D 0
#define RXCIE RXCIE0
#define SIGNATURE_0 0x1E
#define SIGNATURE_1 0x96
#define SIGNATURE_2 0x0A
#define ADC1D 1
#define AVRCOMPAT_H 
#define PRUSART0 1
#define PRUSART1 4
#define ADC2D 2
#define FUSE_SPIEN (unsigned char)~_BV(5)
#define ADC3D 3
#define PORTD3 PD3
#define USART1_TX_vect_num 30
#define ADC4D 4
#define PORTD7 PD7
#define EE_READY_vect _VECTOR(25)
#define PRR0 _SFR_MEM8(0x64)
#define ADC5D 5
#define AVR_STACK_POINTER_LO_ADDR _SFR_IO_ADDR(SPL)
#define ADC6D 6
#define MUX4 4
#define EEPROMFS_SECTORSIZE 64
#define PCINT10 2
#define PCINT11 3
#define PCINT12 4
#define PCINT13 5
#define PCINT14 6
#define PCINT15 7
#define PCINT16 0
#define PCINT17 1
#define PCINT18 2
#define PCINT19 3
#define ADC7D 7
#define OCDR0 0
#define OCDR1 1
#define OCDR2 2
#define OCDR3 3
#define OCDR4 4
#define OCDR5 5
#define OCDR6 6
#define OCDR7 7
#define PCINT20 4
#define PCINT21 5
#define PCINT22 6
#define PCINT24 0
#define PCINT25 1
#define PCINT26 2
#define PCINT27 3
#define PCINT28 4
#define PCINT29 5
#define CLKPR _SFR_MEM8(0x61)
#define PRTIM0 5
#define PRTIM1 3
#define PCINT30 6
#define PCINT31 7
#define SREG _SFR_IO8(0x3F)
#define TXEN TXEN0
#define _SFR_WORD(sfr) _MMIO_WORD(_SFR_ADDR(sfr))
#define RXCIE0 7
#define GPIOR0 _SFR_IO8(0x1E)
#define GPIOR1 _SFR_IO8(0x2A)
#define GPIOR2 _SFR_IO8(0x2B)
#define ISR_NAKED __attribute__((naked))
#define LONGVERSION "-m644p-alnwlsn-custom"
#define AVR_STATUS_ADDR _SFR_IO_ADDR(SREG)
#define SM0 1
#define SM1 2
#define SM2 3
#define U2X0 1
#define U2X1 1
#define SPI_MASK (SPI_SS|SPI_MOSI|SPI_MISO|SPI_SCK)
#define CONFIG_HARDWARE_NAME sd2iec-alnwlsn
#define TIMER2_OVF_vect_num 11
#define TWAM6 7
#define BADISR_vect __vector_default
#define UBRR0 _SFR_MEM16(0xC4)
#define UBRR1 _SFR_MEM16(0xCC)
#define UBRRH UBRR0H
#define UBRRL UBRR0L
#define SPE 6
#define SPH _SFR_IO8(0x3E)
#define SPL _SFR_IO8(0x3D)
#define REFS0 6
#define REFS1 7
#define CONFIG_H 
#define SOFTI2C_DELAY 6
#define CONFIG_COMMAND_BUFFER_SIZE 120
#define PSRASY 1
#define PCINT2_vect _VECTOR(6)
#define PORT1 1
#define PORT2 2
#define PORT3 3
#define PORT4 4
#define PORT5 5
#define PORT6 6
#define PORT7 7
#define ACD 7
#define PORTA _SFR_IO8(0X02)
#define PORTB _SFR_IO8(0x05)
#define PORTC _SFR_IO8(0x08)
#define PORTD _SFR_IO8(0x0B)
#define ACO 5
#define TIMER1_COMPB_vect _VECTOR(14)
#define INT0_vect_num 1
#define WDT_vect _VECTOR(8)
#define HFUSE_DEFAULT (FUSE_BOOTSZ0 & FUSE_BOOTSZ1 & FUSE_SPIEN & FUSE_JTAGEN)
#define OCR2BUB 2
#define _SFR_DWORD(sfr) _MMIO_DWORD(_SFR_ADDR(sfr))
#define TWPS0 0
#define TWPS1 1
#define ADTS1 1
#define OSCCAL _SFR_MEM8(0x66)
#define FUSE_CKOUT (unsigned char)~_BV(6)
#define SD_CHANGE_HANDLER ISR(INT0_vect)
#define TCN2UB 4
#define set_atn_irq(x) if (x) { IEC_PCMSK |= _BV(IEC_PIN_ATN); } else { IEC_PCMSK &= (uint8_t)~_BV(IEC_PIN_ATN); }
#define _SFR_ADDR(sfr) _SFR_MEM_ADDR(sfr)
#define WDTCSR _SFR_MEM8(0x60)
#define SLEEP_MODE_PWR_SAVE (0x03<<1)
#define IEC_OPIN_DATA PA5
#define BODS 6
#define COM2A0 6
#define COM2A1 7
#define MONDR _SFR_IO8(0x31)
#define ICNC1 7
#define COM2B0 4
#define COM2B1 5
#define AS2 5
#define set_sd_led(x) do {} while (0)
#define PB2 2
#define USART0_UDRE_vect _VECTOR(21)
#define TWINT 7
#define _SFR_MEM_ADDR(sfr) (sfr)
#define RWWSB 6
#define AVR 1
#define ICR1H _SFR_MEM8(0x87)
#define ADC_vect _VECTOR(24)
#define USART0_TX_vect _VECTOR(22)
#define PCINT3_vect _VECTOR(7)
#define IEC_BIT_SRQ _BV(IEC_PIN_SRQ)
#define PA0 0
#define PA1 1
#define PA2 2
#define PA3 3
#define PA4 4
#define PA5 5
#define PA6 6
#define PA7 7
#define PB0 0
#define PB1 1
#define PB3 3
#define PB4 4
#define PB5 5
#define PB6 6
#define PB7 7
#define IEC_OUTPUTS_INVERTED 
#define PSRSYNC 0
#define PC0 0
#define PC1 1
#define PC2 2
#define PC3 3
#define PC4 4
#define PC5 5
#define PC6 6
#define PC7 7
#define PORF 0
#define PD0 0
#define PD1 1
#define PD2 2
#define PD3 3
#define PD4 4
#define PD5 5
#define PD6 6
#define PD7 7
#define SD_SUPPLY_VOLTAGE (1L<<18)
#define TIMER2_OVF_vect _VECTOR(11)
#define WGM10 0
#define WGM11 1
#define WGM12 3
#define WGM13 4
#define UPE0 2
#define UPE1 2
#define WGM20 0
#define WGM21 1
#define WGM22 3
#define PORTB0 PB0
#define _AVR_LOCK_H_ 1
#define CONFIG_LOADER_SAMSJOURNEY 
#define CONFIG_LOADER_AR6 
#define _AVR_VERSION_H_ 
#define TIMER1_COMPB_vect_num 14
#define MSTR 4
#define ISR_NOBLOCK __attribute__((interrupt))
#define EEPROMFS_ENTRIES 8
#define IEC_DDROUT IEC_DDR
#define SPI_MISO _BV(PB6)
#define PORT0 0
#define PRR _SFR_MEM8(0x64)
#define IEC_BIT_ATN _BV(IEC_PIN_ATN)
#define PCMSK1 _SFR_MEM8(0x6C)
#define PCINT3_vect_num 7
#define TOIE0 0
#define TOIE1 0
#define TOIE2 0
#define TXC0 6
#define USART0_UDRE_vect_num 21
#define PCICR _SFR_MEM8(0x68)
#define CONFIG_LOADER_ULOAD3 
#define TXC1 6
#define EMPTY_INTERRUPT(vector) void vector (void) __attribute__ ((signal,naked,__INTR_ATTRS)); void vector (void) { __asm__ __volatile__ ("reti" ::); }
#define PCINT23 7
#define PUD 4
#define IEC_OBIT_DATA _BV(IEC_OPIN_DATA)
#define BODSE 5
#define PCIE0 0
#define PCIE1 1
#define PCIE2 2
#define PCIE3 3
#define EERIE 3
#define UCPHA0 1
#define PCIF0 0
#define PCIF1 1
#define PCIF2 2
#define PCIF3 3
#define TCNT1L _SFR_MEM8(0x84)
#define PCIFR _SFR_IO8(0x1B)
#define ISR_ALIASOF(v) __attribute__((alias(__STRINGIFY(v))))
#define FUSE_OCDEN (unsigned char)~_BV(7)
#define _SFR_BYTE(sfr) _MMIO_BYTE(_SFR_ADDR(sfr))
#define ADCSRA _SFR_MEM8(0x7A)
#define ADCSRB _SFR_MEM8(0x7B)
#define UMSEL00 6
#define UMSEL01 7
#define _BV(bit) (1 << (bit))
#define SE 0
#define SP _SFR_IO16(0x3D)
#define WGM01 1
#define IEC_ATN_HANDLER ISR(IEC_ATN_INT_VECT)
#define WGM02 3
#define UMSEL10 6
#define UMSEL11 7
#define USART0_TX_vect_num 22
#define TIMSK0 _SFR_MEM8(0x6E)
#define TIMSK1 _SFR_MEM8(0x6F)
#define TIMSK2 _SFR_MEM8(0x70)
#define IVSEL 1
#define CONFIG_LOADER_WHEELS 
#define RXC0 7
#define RXC1 7
#define TIMER2_COMPA_vect _VECTOR(9)
#define SLEEP_MODE_IDLE (0x00<<1)
#define INT0_vect _VECTOR(1)
#define CONFIG_LOADER_NIPPON 
#define UBRR0H _SFR_MEM8(0xC5)
#define XH r27
#define UBRR0L _SFR_MEM8(0xC4)
#define XL r26
#define RXEN RXEN0
#define _SFR_MEM16(mem_addr) (mem_addr)
#define UBRR1H _SFR_MEM8(0xCD)
#define YH r29
#define UBRR1L _SFR_MEM8(0xCC)
#define YL r28
#define PRTIM2 6
#define SLEEP_MODE_EXT_STANDBY (0x07<<1)
#define ZL r30
#define _SFR_MEM32(mem_addr) (mem_addr)
#define UCSRB UCSR0B
#define TIMER1_OVF_vect _VECTOR(15)
#define ISR(vector,...) void vector (void) __attribute__ ((signal,__INTR_ATTRS)) __VA_ARGS__; void vector (void)
#define SOFTI2C_BIT_INTRQ PC6
#define GTCCR _SFR_IO8(0x23)
#define SPMCSR _SFR_IO8(0x37)
#define TIFR0 _SFR_IO8(0x15)
#define TIFR1 _SFR_IO8(0x16)
#define TIFR2 _SFR_IO8(0x17)
#define ADLAR 5
#define TSM 7
#define ISC00 0
#define ICF1 5
#define ISC01 1
#define ISR_ALIAS(vector,tgt) void vector (void) __attribute__((signal, naked, __INTR_ATTRS)); void vector (void) { asm volatile ("jmp " __STRINGIFY(tgt) ::); }
#define PCMSK0 _SFR_MEM8(0x6B)
#define PCMSK2 _SFR_MEM8(0x6D)
#define PCMSK3 _SFR_MEM8(0x73)
#define TIMER1_COMPA_vect_num 13
#define ADPS2 2
#define EIMSK _SFR_IO8(0x1D)
#define TXC TXC0
#define FUSE_CKDIV8 (unsigned char)~_BV(7)
#define IEC_OBIT_SRQ _BV(IEC_OPIN_SRQ)
#define VERSION "1.0.0atentdead0"
#define BLBSET 3
#define WCOL 6
#define PCINT2_vect_num 6
#define CONFIG_UART_BAUDRATE 19200
#define FUSE_SUT0 (unsigned char)~_BV(4)
#define FUSE_SUT1 (unsigned char)~_BV(5)
#define WGM00 0
#define F_CPU 8000000UL
#define SPM_PAGESIZE 256
#define ICR1 _SFR_MEM16(0x86)
#define USART_UDRE_vect USART0_UDRE_vect
#define USART0_RX_vect _VECTOR(20)
#define TCNT0 _SFR_IO8(0X26)
#define TCNT1 _SFR_MEM16(0x84)
#define TCNT2 _SFR_MEM8(0xB2)
#define TIMER2_COMPB_vect _VECTOR(10)
#define PRSPI 2
#define INT1_vect _VECTOR(2)
#define TXEN0 3
#define TXEN1 3
#define AVR_STACK_POINTER_REG SP
#define JTRF 4
#define ACIS0 0
#define ACIS1 1
